### ISSUE TITLE
Errors in the list part

### ISSUE THREAD

**Issue by louis-etne** [space1649/8-bit-SAP-Breadboard-Computer-by-Space-Man#1]
Hello !  
Thanks for your files, it's so useful! There is an error for the 330Ω resistor, it's this [link](https://www.jameco.com/z/CF1-4W331JRC-Resistor-Carbon-Film-330-Ohm-1-4-Watt-5-_690742.html).

And I have a question: Where did you find your _Double-pole toggle switch_?

Thanks!

**Comment by space1649** [comment]
Thanks for catching that.  I found the latching switches on ebay.  Search for 
15 x Push Button Switch Latching DPDT 0.5A 50VDC 8x8mm  [Link](http://www.ebay.com/itm/322171845157?_trksid=p2057872.m2749.l2649&ssPageName=STRK%3AMEBIDX%3AIT)
